O engenheiro de dados da sua empresa forneceu acesso a dois conjuntos de dados pré-processados. Agora, cabe a você analisá-los cuidadosamente para identificar quais escolas utilizaram seus recursos de forma mais eficiente na preparação de estudantes que se destacaram nas Olimpíadas de Redação e de Matemática.

In [ ]:
import pandas as pd

escolas = pd.read_csv('https://drive.google.com/uc?id=1Jgto7psHaMRTAVzcFt7D6SgJiHMB7uGT')
estudantes = pd.read_csv('https://drive.google.com/uc?id=15aOJIGAyLMSY1gecjiCgu2ko_riIcKQy')

Como visualizamos o DataFrame escolas?

In [ ]:
escolas

    ID_Escola Nome_Escola Tipo_Escola  Numero_Alunos  Orcamento_Anual
0           0    Escola A     Publica           2917          1910635
1           1    Escola B     Publica           2949          1884411
2           2    Escola C  Particular           1761          1056600
3           3    Escola D     Publica           4635          3022020
4           4    Escola E  Particular           1468           917500
5           5    Escola F  Particular           2283          1319574
6           6    Escola G  Particular           1858          1081356
7           7    Escola H     Publica           4976          3124928
8           8    Escola I  Particular            427           248087
9           9    Escola J  Particular            962           585858
10         10    Escola K  Particular           1800          1049400
11         11    Escola L     Publica           3999          2547363
12         12    Escola M     Publica           4761          3094650
13         13    Escola N     Publica           2739          1763916
14         14    Escola O  Particular           1635          1043130

E o estudantes?

In [ ]:
estudantes

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica
0,0,Kevin Bradley,M,6,Escola A,66,79
1,1,Paul Smith,M,9,Escola A,94,61
2,2,John Rodriguez,M,9,Escola A,90,60
3,3,Oliver Scott,M,9,Escola A,67,58
4,4,William Ray,F,6,Escola A,97,84
...,...,...,...,...,...,...,...
39155,39155,John Brooks,M,7,Escola O,92,98
39156,39156,Stephanie Contreras,F,8,Escola O,79,95
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94
39158,39158,Kari Holloway,F,7,Escola O,87,90
39159,39159,Kimberly Cabrera,F,8,Escola O,85,72

In [ ]:
escolas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Escola        15 non-null     int64
 1   Nome_Escola      15 non-null     object
 2   Tipo_Escola      15 non-null     object
 3   Numero_Alunos    15 non-null     int64
 4   Orcamento_Anual  15 non-null     int64
dtypes: int64(3), object(2)
memory usage: 728.0+ bytes

Já conhecemos o DataFrame escolas, mas como podemos obter mais informações sobre o estudantes?

In [1]:
estudantes.info()

NameError: name 'estudantes' is not defined

In [ ]:
estudantes.describe()

       ID_Estudante         Serie  Nota_Redacao  Nota_Matematica
count  39160.000000  39160.000000  39160.000000     39160.000000
mean   19579.500000      7.359551     81.875741        78.984934
std    11304.662607      1.102796     10.238839        12.311055
min        0.000000      6.000000     63.000000        55.000000
25%     9789.750000      6.000000     73.000000        69.000000
50%    19579.500000      7.000000     82.000000        79.000000
75%    29369.250000      8.000000     91.000000        89.000000
max    39159.000000      9.000000     99.000000        99.000000

In [ ]:
categoricas = ['Genero', 'Nome_Estudante', 'Nome_Escola']
estudantes[categoricas].describe()

       Genero Nome_Estudante Nome_Escola
count   39160          39160       39160
unique      2          32539          15
top         F  Michael Smith    Escola H
freq    19728             26        4976

In [ ]:
estudantes.isna().sum()

ID_Estudante       0
Nome_Estudante     0
Genero             0
Serie              0
Nome_Escola        0
Nota_Redacao       0
Nota_Matematica    0
dtype: int64

Perguntas:

Existem dados faltantes nas tabelas? Não


Existe algo em comum nas duas tabelas? Nome_Escola

### Combinando os DataFrames:

In [ ]:
data = pd.merge(estudantes, escolas, how='left')

In [ ]:
data.head(10)

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
0,0,Kevin Bradley,M,6,Escola A,66,79,0,Publica,2917,1910635
1,1,Paul Smith,M,9,Escola A,94,61,0,Publica,2917,1910635
2,2,John Rodriguez,M,9,Escola A,90,60,0,Publica,2917,1910635
3,3,Oliver Scott,M,9,Escola A,67,58,0,Publica,2917,1910635
4,4,William Ray,F,6,Escola A,97,84,0,Publica,2917,1910635
5,5,James Miranda,M,6,Escola A,94,94,0,Publica,2917,1910635
6,6,Benjamin Carter,F,8,Escola A,82,80,0,Publica,2917,1910635
7,7,Mason Baker,F,9,Escola A,96,69,0,Publica,2917,1910635
8,8,Ethan Roth,M,7,Escola A,95,87,0,Publica,2917,1910635
9,9,Jacob Greene,M,7,Escola A,96,84,0,Publica,2917,1910635

Obter as informações do novo conjunto de dados:

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39160 entries, 0 to 39159
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Estudante     39160 non-null  int64
 1   Nome_Estudante   39160 non-null  object
 2   Genero           39160 non-null  object
 3   Serie            39160 non-null  int64
 4   Nome_Escola      39160 non-null  object
 5   Nota_Redacao     39160 non-null  int64
 6   Nota_Matematica  39160 non-null  int64
 7   ID_Escola        39160 non-null  int64
 8   Tipo_Escola      39160 non-null  object
 9   Numero_Alunos    39160 non-null  int64
 10  Orcamento_Anual  39160 non-null  int64
dtypes: int64(7), object(4)
memory usage: 3.3+ MB

Entendendo as variáveis categóricas:

In [ ]:
data["Serie"].unique()

array([6, 9, 8, 7])

In [ ]:
data.Serie.value_counts()

Serie
6    11406
7    10165
8     9692
9     7897
Name: count, dtype: int64

Algumas perguntas:

Qual o orçamento total das escolas?

Qual a nota média dos alunos nas disciplinas analisadas?

In [ ]:
data["Orcamento_Anual"].unique().sum()

24649428

In [ ]:
escolas['Orcamento_Anual'].sum()

24649428

Vamos considerar que alto desempenho sejam notas maiores que 90. Quantos alunos ficaram com nota superior a 90 em redação? E qual o percentual?

In [ ]:
HighRed = data[data['Nota_Redacao'] >= 90]
len(HighRed)

11077

In [ ]:
(len(data[data['Nota_Redacao'] >= 90]) / len(data)) * 100

28.286516853932586

Quantos eram de escola pública?

In [ ]:
len(data[(data['Tipo_Escola'] == 'Publica') & (data['Nota_Redacao'] > 90)])

6478

Quantos alunos ficaram com nota superior a 90 em matemática? E qual o percentual?

In [ ]:
HighMat = estudantes.query('Nota_Matematica > 90')
len(HighMat)

8834

Quantos eram do sexo feminino?

In [ ]:
HighMat[HighMat['Genero'] == 'F']

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica
41,41,Jennifer Parks,F,8,Escola A,85,95
45,45,Heidi Jackson,F,8,Escola A,64,93
49,49,Natalie Mitchell,F,7,Escola A,73,93
50,50,Tiffany Gutierrez,F,7,Escola A,82,95
105,105,Alexis Todd,F,8,Escola A,82,95
...,...,...,...,...,...,...,...
39138,39138,Monica Hampton,F,6,Escola O,94,94
39140,39140,Cheyenne Hernandez,F,6,Escola O,76,99
39149,39149,Glenda Fletcher,F,8,Escola O,82,93
39156,39156,Stephanie Contreras,F,8,Escola O,79,95
39157,39157,Kristen Gonzalez,F,6,Escola O,79,94

Quantos alunos tiraram notas maior que 90 nas duas provas?

In [ ]:
data[(data['Nota_Matematica']>=90) & (data['Nota_Redacao']>=90)]

,ID_Estudante,Nome_Estudante,Genero,Serie,Nome_Escola,Nota_Redacao,Nota_Matematica,ID_Escola,Tipo_Escola,Numero_Alunos,Orcamento_Anual
5,5,James Miranda,M,6,Escola A,94,94,0,Publica,2917,1910635
30,30,Bobby Harris,M,6,Escola A,94,99,0,Publica,2917,1910635
32,32,Candace Phelps,F,8,Escola A,93,90,0,Publica,2917,1910635
91,91,Mark Cherry,M,7,Escola A,96,98,0,Publica,2917,1910635
133,133,Marisa Lowe,F,6,Escola A,95,95,0,Publica,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39110,39110,Sharon Nguyen,F,8,Escola O,91,90,14,Particular,1635,1043130
39121,39121,Stephanie Wilson,F,7,Escola O,94,94,14,Particular,1635,1043130
39127,39127,Robert Wood,M,6,Escola O,97,98,14,Particular,1635,1043130
39138,39138,Monica Hampton,F,6,Escola O,94,94,14,Particular,1635,1043130
39155,39155,John Brooks,M,7,Escola O,92,98,14,Particular,1635,1043130

Como ficou a distribuição dos alunos de alto desempenho pela série?

In [ ]:
HighBoth = data[(data['Nota_Matematica'] > 90) & (data['Nota_Redacao'] > 90)]
data[HighBoth][Serie].value_counts

ValueError: Boolean array expected for the condition, not object

Qual o total por escolas?

### Tarefa:

Quais escolas demonstraram maior eficiência?

Instruções:

1. Antes de analisar os dados, explique o que significa "eficiência" no contexto de escolas. Considere aspectos como o uso de recursos, desempenho acadêmico, custo-benefício, entre outros critérios relevantes.
   
2. Utilize os dados fornecidos neste documento para identificar quais escolas se destacam em termos de eficiência, de acordo com a definição estabelecida.

3. Quais diferentes formas de análise, novos resultados ou novas métricas podem ajudar a avaliar melhor a eficiência das escolas?